[0m21:57:02.278318 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002069A7E22D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002069A810D90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002069A7E23D0>]}


============================== 21:57:02.315896 | adf90602-a8e4-4812-97a1-1b50d95fbf96 ==============================
[0m21:57:02.315896 [info ] [MainThread]: Running with dbt=1.8.5
[0m21:57:02.316896 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Luciano\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init', 'log_format': 'default', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m21:57:10.908567 [debug] [MainThread]: Starter project path: C:\Users\Luciano\workspace\lvgalvaofilho\dbt_dashboard_aovivo\.venv\Lib\site-packages\dbt\include\starter_project
[0m21:57:10.953743 [info ] [MainThread]: 
Your new dbt project "dbt_aovivo" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m21:57:10.954742 [info ] [MainThread]: Setting up your profile.
[0m21:58:21.047751 [info ] [MainThread]: Profile dbt_aovivo written to C:\Users\Luciano\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m21:58:21.048750 [debug] [MainThread]: Command `dbt init` succeeded at 21:58:21.048750 after 78.83 seconds
[0m21:58:21.049750 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020697F94890>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020692EF4390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002069A3A9DD0>]}
[0m21:58:21.049750 [debug] [MainThread]: Flushing usage events
[0m21:58:28.322192 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276FA984410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276FA984150>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276FA984990>]}


============================== 21:58:28.325201 | c3953edd-65c2-46a9-8d7b-8aed45b3ead6 ==============================
[0m21:58:28.325201 [info ] [MainThread]: Running with dbt=1.8.5
[0m21:58:28.326197 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Luciano\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt debug', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m21:58:28.360028 [info ] [MainThread]: dbt version: 1.8.5
[0m21:58:28.360028 [info ] [MainThread]: python version: 3.11.5
[0m21:58:28.361031 [info ] [MainThread]: python path: C:\Users\Luciano\workspace\lvgalvaofilho\dbt_dashboard_aovivo\.venv\Scripts\python.exe
[0m21:58:28.361031 [info ] [MainThread]: os info: Windows-10-10.0.22631-SP0
[0m21:58:28.367140 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.bigquery'
[0m21:58:28.369140 [info ] [MainThread]: Error importing adapter: No module named 'dbt.adapters.bigquery'
[0m21:58:28.417358 [info ] [MainThread]: Using profiles dir at C:\Users\Luciano\.dbt
[0m21:58:28.417358 [info ] [MainThread]: Using profiles.yml file at C:\Users\Luciano\.dbt\profiles.yml
[0m21:58:28.418358 [info ] [MainThread]: Using dbt_project.yml file at C:\Users\Luciano\workspace\lvgalvaofilho\dbt_dashboard_aovivo\dbt_project.yml
[0m21:58:28.418358 [info ] [MainThread]: Configuration:
[0m21:58:28.419360 [info ] [MainThread]:   profiles.yml file [[31mERROR invalid[0m]
[0m21:58:28.419360 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m21:58:28.420359 [info ] [MainThread]: Required dependencies:
[0m21:58:28.420359 [debug] [MainThread]: Executing "git --help"
[0m21:58:28.436384 [debug] [MainThread]: STDOUT: "b"usage: git [-v | --version] [-h | --help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--config-env=<name>=<envvar>] <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m21:58:28.437380 [debug] [MainThread]: STDERR: "b''"
[0m21:58:28.437380 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m21:58:28.438380 [info ] [MainThread]: Connection test skipped since no profile was found
[0m21:58:28.438380 [info ] [MainThread]: [31m2 checks failed:[0m
[0m21:58:28.439381 [info ] [MainThread]: Could not load dbt_project.yml
Profile loading failed for the following reason:
Runtime Error
  Credentials in profile "analytics", target "dev" invalid: Runtime Error
    Could not find adapter type bigquery!

Runtime Error
  Credentials in profile "datawarehouse", target "dev" invalid: Runtime Error
    Could not find adapter type bigquery!


[0m21:58:28.440381 [info ] [MainThread]: Project loading failed for the following reason:
 project path <C:\Users\Luciano\workspace\lvgalvaofilho\dbt_dashboard_aovivo\dbt_project.yml> not found

[0m21:58:28.440381 [debug] [MainThread]: Command `dbt debug` failed at 21:58:28.440381 after 0.18 seconds
[0m21:58:28.441887 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276F43C4390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276FA9788D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000276FA9E2110>]}
[0m21:58:28.441887 [debug] [MainThread]: Flushing usage events
